[TS] Typescript bot (approach #2)
bartekkustra/zsrs-discordbot pull request #4
Opened 2021-02-24 16:09 UTC by bartekkustra

2021-02-24 17:11 UTC, mhalas approved these changes

2021-02-24 22:08 UTC, jstuczyn requested changes
Minor changes required.

2021-02-24 22:08 UTC, jstuczyn commented on python/.gitignore
> +.env
Czemu zostały jakiekolwiek pliki związane z pythonem?

2021-02-24 22:08 UTC, jstuczyn commented on src/features/edyta.ts
> +  const regexp = new RegExp(`(^|\\W)(${arr.join('|')})`)
Nie do końca dobry ten regex. Nie złapie np  "aaaedyta", co jest dobrze, ale za to złapie "edytaaaa". Zmień na `(^|\W)(edyta|edyto|etc)\W`

2021-02-24 22:08 UTC, jstuczyn commented on src/features/url.ts
> +  if (msg.content.length > 10) {
Ja bym wrzucił to "10" w jakiegoś constanta żeby wiedzieć skąd to się wzieło

2021-02-24 22:08 UTC, jstuczyn commented on src/features/url.ts
> +            msg.delete()
Jak już doszliśmy tak daleko, to po sprawdzajmy po blackliscie parameters i tyle te usuwajmy (i.e. `fbclid`, `utm_source`, etc. co wysłalem)

2021-02-24 22:08 UTC, jstuczyn commented on src/features/edyta.ts
> +    'eԁyta',
duplicate

2021-02-26 11:21 UTC, bartekkustra commented on src/features/url.ts
> +            msg.delete()
Nie w tym PR, ale śmiało napisz Issue i podziałaj z nowym PR ;P

2021-02-26 11:23 UTC, jstuczyn approved these changes
![](https://i.imgur.com/SnIwFtR.gif)

2021-02-26 17:50 UTC, merged